# Generated by Django 4.2.15 on 2024-08-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filetree", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filetreeitem",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
